name: Staging

on:
  push:
    branches:
      - staging

jobs:
  update_index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Check for build
      # Setup Python
      # Build index

      - name: Check for build, index.html and deployments.json
        run: |
          # ------------
          # Ensure files
          # ------------

          declare -a missing
          
          if ! [[ -d "./build" ]]; then
            missing+=("build")
          fi

          if ! [[ -f "./build/deployments.json" ]]; then
            missing+=("build/deployments.json")
          fi
          
          if ! [[ -f "./index.html" ]]; then
            missing+=("index.html")
          fi
          
          if ! [[ ${#missing[*]} -eq 0 ]]
          then
            exit 0
          else
            echo "::error ::Missing ${missing[@]} from 'staging' branch."
            exit 1
          fi

      - uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Update index.html, parse opt-outs
        run: |
          pip install -r ./scripts/requirements.txt
          python ./scripts/update_root_index.py

  deploy_to_production:
    runs-on: ubuntu-latest
    if: ${{ always() && contains(join(needs.*.result, ','), 'success') }}
    needs: [update_index]
    steps:
      - uses: actions/checkout@v3

      # Push './build' and './index.html' to production

      - name: Push build to production
        env:
          SRC_FOLDER_PATH: build
          TARGET_BRANCH: production
        run: |
          files=$(find $SRC_FOLDER_PATH -type f)
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git fetch
          git checkout $TARGET_BRANCH
          git checkout ${GITHUB_REF##*/} -- $files
          git add -A
          git diff-index --quiet HEAD ||  git commit -am "deploy files"
          git push origin $TARGET_BRANCH

      - name: Push index.html to production
        env:
          TARGET_BRANCH: production
        run: |
          files="index.html"
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add -A
          git commit -m "Updating index.html"
          git fetch
          git checkout $TARGET_BRANCH
          git checkout ${GITHUB_REF##*/} -- $files
          git diff-index --quiet HEAD ||  git commit -am "deploy files"
          git push origin $TARGET_BRANCH
