name: Staging

on:
  push:
    branches:
      - staging

jobs:
  prep_staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Prepping staging

      - name: Check if web/ and index.html have been pushed
        run: |
          if [[ -d "web" ]] && [[ -f "index.html" ]]
          then
            exit 0
          else
            echo "::error ::Missing 'web' or 'index.html' from 'staging' branch."
            exit 1
          fi

  update_deployment:
    runs-on: ubuntu-latest
    if: ${{ always() && contains(join(needs.*.result, ','), 'success') }}
    needs: [prep_staging]
    steps:
      - uses: actions/checkout@v3

      # Push web to production

      - name: Commit all contents under web/ to production
        uses: EndBug/add-and-commit@v9
        with:
          add: "web/**"
          push: origin production --set-upstream --force

      # Checkout to production & peek list of subdirectories

      - uses: actions/checkout@v3
        with:
          ref: production

      - name: Fetch subdirs from production
        id: subdirs
        run: |
          if [[ -d "web" ]]
          then
            subdirs=$(ls web)
            echo "include=$subdirs" >> $GITHUB_OUTPUT
            echo "=> Found: $subdirs"
          else
            echo "::error ::Missing 'web' from 'production' branch."
            exit 1
          fi

      # Update index.html, passing to_remove to next step for deletion

      - uses: actions/checkout@v3
        with:
          ref: staging

      - name: Update index.html, parse opt-outs
        id: update_index
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: |
          including="${{ github.subdirs.outputs.include }}"
          excluding="${{ github.event.head_commit.message }}"
          pip install -r ./scripts/requirements.txt
          to_remove=$(python ./scripts/update_root_index.py "$including" "$excluding")
          echo "to_remove=$to_remove" >> $GITHUB_OUTPUT
          echo "=> To remove: $to_remove"

      # Push index.html to production and remove opted-out

      - name: Commit index.html, remove opt-outs
        uses: EndBug/add-and-commit@v9
        with:
          add: "index.html"
          remove: "${{ github.update_index.outputs.to_remove }}"
          push: "origin production --force"
