name: Staging

on:
  push:
    branches:
      - staging

jobs:
  update_deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: staging

      # Update root index

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: |
          pip install -r ./scripts/requirements.txt
          python ./scripts/update_root_index.py

      # Push committed + updated root index to production

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: "--all"
          push: "origin production"
